- name: Dotfiles
  hosts: localhost
  tasks:
    - name: Clone dotfiles
      git:
        repo: "https://www.github.com/lailanater/dotfiles.git"
        dest: "~/dotfiles"

    - name: Stow files
      command:
        cmd: ./dots
        chdir: "~/dotfiles"
