- name: Fix frozen or unresponsive display (flip_done timed out) (GRUB)
  hosts: localhost
  become: true
  tasks:
    - name: Query for acpi in kernel params
      shell: grep -E -e '^GRUB_CMDLINE_LINUX_DEFAULT=".* amdgpu.dcdebugmask=' /etc/default/grub
      register: amdgpu_dcdebugmask_kernel_param
      ignore_errors: true

    - when: amdgpu.dcdebugmask_kernel_param.rc == 1
      block:
        - name: Add amdgpu_dcdebugmask kernel param
          shell: sed -i.{{ ansible_date_time.iso8601 }}.bak -E "s/^GRUB_CMDLINE_LINUX_DEFAULT=\"(.*)\"/GRUB_CMDLINE_LINUX_DEFAULT=\"\1 amdgpu.dcdebugmask=0x10\"/" /etc/default/grub

        - import_tasks: ../../tasks/grub-rebuild.yml
