- name: Edit Steam config
  hosts: localhost
  tasks:
    - name: Check if steam_dev.cfg exists
      register: steam_dev_stats
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.steam/steam/steam_dev.cfg"

    - name: Start Steam once to generate config files
      when: steam_dev_stats.stat.exists == false
      shell: timeout 8 steam
      register: result
      failed_when: result.rc != 124

    - name: Fix steam download speed
      lineinfile:
        path: "{{ ansible_env.HOME }}/.steam/steam/steam_dev.cfg"
        search_string: "@nClientDownloadEnableHTTP2PlatformLinux"
        line: "@nClientDownloadEnableHTTP2PlatformLinux 0"
        create: true

    - name: Get number of threads to use
      shell: if [[ $(nproc) -le 2 ]]; then echo 1; else echo $(($(nproc) - 2)); fi
      register: nproc_output

    - name: Enable shaders to use all but 2 threads
      lineinfile:
        path: "{{ ansible_env.HOME }}/.steam/steam/steam_dev.cfg"
        search_string: "unShaderBackgroundProcessingThreads"
        line: "unShaderBackgroundProcessingThreads {{ nproc_output.stdout }}"
