- hosts: localhost
  tasks:
    - name: Get user info
      set_fact:
        user_name: "{{ ansible_env.USER }}"

- name: Zsh
  hosts: localhost
  become: yes
  tasks:
    - name: Set ZSH as default shell
      shell:
        cmd: "chsh -s /bin/zsh {{ user_name }}"
