- name: Fedora
  hosts: localhost
  become: true
  tasks:
    - name: Upgrade/update dnf
      dnf:
        name:
            - steam
            - fastfetch
            - neovim
            - gh
            - git
        state: present

- import_playbook: dnf_programs.yml
