- name: Main
  hosts: localhost
  become: true
  tasks:
    - name: Dist Upgrade
      community.general.zypper:
        name: '*'
        state: dist-upgrade
    - include_tasks: "{{ item }}"
      loop:
        - tasks/core.yml
        - tasks/1password.yml
        - tasks/gaming.yml
