- name: Main
  hosts: localhost
  become: true
  tasks:
    - name: Upgrade/update pacman
      community.general.pacman:
        upgrade: true
        update_cache: true
    - include_tasks: "{{ item }}"
      loop:
        - tasks/core.yml
        - tasks/1password.yml
        - tasks/gaming.yml
