- block:
  - name: Get 1Password signing key
    shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import
  become_user: "{{ ansible_user_id }}"

- block:
  - name: Clean 1Password directory
    file:
      path: "/home/{{ ansible_user_id }}/dev/1password"
      state: absent
  become_user: root

- block:
  - name: Clone 1Password
    shell:
      cmd: git clone https://aur.archlinux.org/1password.git
      chdir: "/home/{{ ansible_user_id }}/dev"

  - name: Install 1Password
    shell:
      cmd: makepkg -si --noconfirm
      chdir: "/home/{{ ansible_user_id }}/dev/1password"
  become_user: "{{ ansible_user_id }}"
