- block:
    - name: Add the key for the 1Password RPM repository
      shell: sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
      become_user: root

- block:
    - name: Add the 1Password RPM repository
      shell: sudo zypper addrepo https://downloads.1password.com/linux/rpm/stable/x86_64 1password
      become_user: root

- block:
    - name: Install 1Password
      community.general.zypper:
        name: 1password
        state: present
