- block:
    - name: Install core libraries
      community.general.zypper:
        name:
          - easyeffects
          - stow
          - alacritty
          - neovim
          - btop
          - firefox
          - git
          - zsh
          - eza
          - neofetch
          - starship
          - opi
          - nodejs
          - gh
        state: present

- block:
    - name: Install opi libraries
      shell: opi -n -m codecs zsh-completions zsh-autosuggestions

- block:
    - name: Set zsh as default shell
      shell: sudo chsh -s $(which zsh)
      become_user: root

- block:
    - name: Execute stow
      shell: git clone https://github.com/Lailanater/dotfiles.git && cd dotfiles && stow */
