- name: Install core libraries
  community.general.pacman:
    name:
      - discord-screenaudio
      - partitionmanager
      - easyeffects
      - grub-customizer
      - stow
      - alacritty
      - neovim
    state: present
  community.general.pacman:
    name:
      - cachy-browser
    state: absent
