- block:
    - name: Install core libraries
      community.general.zypper:
        name:
          - easyeffects
          - stow
          - alacritty
          - neovim
          - btop
          - firefox
          - git
          - zsh
          - eza
          - neofetch
          - starship
          - opi
        state: present

- block:
    - name: Install opi libraries
      shell: opi -n codecs
