- name: Install core libraries
  community.general.pacman:
    name:
      - vencord
      - partitionmanager
      - easyeffects
      - grub-customizer
      - stow
      - alacritty
      - neovim
      - btop
      - firefox
      - git
      - base-devel
      - snapper
      - btrfs-assistant
      - zsh
      - pipewire
      - wireplumber
      - polkit-kde-agent
      - qt5-wayland
      - qt6-wayland
      - intellij-idea-ultimate-edition
    state: present

- name: Remove default libraries
  community.general.pacman:
    name:
      - kitty
    state: absent
