- name: Setup Vesktop for Install
  hosts: localhost
  tasks:
    - name: Download Vesktop
      command: wget -O ~/Downloads/vesktop.rpm https://vencord.dev/download/vesktop/amd64/rpm

    - name: Ensure folder exists
      file:
        path: "{{ ansible_env.HOME }}/.config/vesktop/themes"
        state: directory
