- name: 1Password
  hosts: localhost
  become: true
  tasks:
    - name: Get the 1Password signing key
      shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

    - name: Check is 1Password is already installed
      ansible.builtin.shell: command -v 1password
      register: onepassword_exists
      ignore_errors: true

    - when: onepassword_exists is failed
      block:
        - name: Get the 1Password signing key for aur_builder
          become_user: aur_builder
          shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

        - name: Clone 1Password
          become_user: aur_builder
          git:
            repo: https://aur.archlinux.org/1password.git
            dest: /home/aur_builder/1password

        - name: Install 1Password
          become_user: aur_builder
          command:
            cmd: makepkg -si --noconfirm
            chdir: /home/aur_builder/1password

        - name: Recursively remove directory
          become_user: aur_builder
          ansible.builtin.file:
            path: /home/aur_builder/1password
            state: absent

    - name: Install 1Password CLI
      shell:
        wget "https://cache.agilebits.com/dist/1P/op2/pkg/v2.31.1/op_linux_amd64_v2.31.1.zip" -O op.zip && \
        unzip -d op op.zip && \
        mv op/op /usr/local/bin/ && \
        rm -r op.zip op && \
        groupadd -f onepassword-cli && \
        chgrp onepassword-cli /usr/local/bin/op && \
        chmod g+s /usr/local/bin/op
