- name: 1Password CLI
  hosts: localhost
  become: true
  tasks:
    - name: Check if 1Password CLI is already installed
      shell: command -v op
      register: has_op_installed
      ignore_errors: true

    - name: Install 1Password CLI
      when: has_op_installed == 1
      shell:
        wget "https://cache.agilebits.com/dist/1P/op2/pkg/v2.31.1/op_linux_amd64_v2.31.1.zip" -O op.zip && \
        unzip -d op op.zip && \
        mv op/op /usr/local/bin/ && \
        rm -r op.zip op && \
        groupadd -f onepassword-cli && \
        chgrp onepassword-cli /usr/local/bin/op && \
        chmod g+s /usr/local/bin/op
