- name: Pacman
  hosts: localhost
  become: true
  tasks:
    - name: Run the equivalent of "pacman -Syu" as a separate step
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install programs from pacman
      community.general.pacman:
        name:
          - lib32-vulkan-radeon
          - steam
          - fastfetch
          - neovim
          - github-cli
          - git
          - stow
          - btop
          - rocm-smi-lib
          - wl-clipboard
          - virt-manager
          - qemu-full
          - speech-dispatcher
          - system-config-printer
          - cups
          - cups-filters
          - cups-pdf
          - dnsmasq
          - power-profiles-daemon
          - kcalc
          - pacman-contrib
          - man-db
          - easyeffects
          - mangohud
          - docker
          - docker-compose
          - docker-buildx
          - firefox
          - gamemode
          - solaar
          - zsh
          - rustup
          - go
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - chromium
          - audacity
          - vlc
          - fzf
          - ripgrep
          - fd
          - curl
          - discord
          - gamescope
          - inotify-tools
          - lshw
          - nvtop
          - tmux
          - obs-studio
          - rclone
          - expect
          - syncthing
          - unzip
          - flatpak
          - wezterm
          - eza
          - starship
          - lsp-plugins-lv2
          - partitionmanager
          - noto-fonts-cjk
          - kwalletmanager
          - yubikey-manager
          - pam-u2f
          - lazygit
          - python-pipx
        state: present

    - name: Create backup of pacman.conf
      copy:
        src: /etc/pacman.conf
        dest: /etc/pacman.conf.{{ ansible_date_time.iso8601 }}.bak

    - name: Check if ILoveCandy option is present
      shell: grep "ILoveCandy" /etc/pacman.conf
      register: i_love_candy_grep
      ignore_errors: true

    - when: i_love_candy_grep.rc == 1
      name: Enable ILoveCandy option
      shell: sed -i '/^\[options\]$/a ILoveCandy' /etc/pacman.conf

    - name: Check if Color option is enabled
      shell: grep "^Color" /etc/pacman.conf
      register: color_grep
      ignore_errors: true

    - when: color_grep.rc == 1
      name: Enable Color option
      shell: sed -i 's/^#Color/Color/' /etc/pacman.conf

    - name: Check if VerbosePkgLists option is enabled
      shell: grep "^VerbosePkgLists" /etc/pacman.conf
      register: verbose_pkg_lists_grep
      ignore_errors: true

    - when: verbose_pkg_lists_grep.rc == 1
      name: Enable VerbosePkgLists option
      shell: sed -i 's/^#VerbosePkgLists/VerbosePkgLists/' /etc/pacman.conf

    - when: i_love_candy_grep.rc == 0 and color_grep.rc == 0 and verbose_pkg_lists_grep.rc == 0
      name: Remove pacman backup since nothing changed
      shell: rm /etc/pacman.conf.{{ ansible_date_time.iso8601 }}.bak
