- name: Pacman
  hosts: localhost
  become: true
  tasks:
    - name: Run the equivalent of "pacman -Syu" as a separate step
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install programs from pacman
      community.general.pacman:
        name:
          - lib32-vulkan-radeon
          - steam
          - fastfetch
          - neovim
          - github-cli
          - git
          - stow
          - btop
          - rocm-smi-lib
          - os-prober
          - wl-clipboard
          - virt-manager
          - qemu-full
          - speech-dispatcher
          - system-config-printer
          - cups
          - cups-filters
          - cups-pdf
          - dnsmasq
          - power-profiles-daemon
          - kcalc
          - reflector
          - pacman-contrib
          - man-db
          - easyeffects
          - mangohud
          - docker
          - docker-compose
          - docker-buildx
          - firefox
          - gamemode
          - solaar
          - zsh
          - rustup
          - go
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - chromium
          - audacity
          - vlc
          - fzf
          - discord
          - gamescope
          - inotify-tools
          - lshw
          - nvtop
          - tmux
          - obs-studio
          - rclone
          - expect
          - syncthing
          - unzip
          - flatpak
          - snap-pac
          - grub-btrfs
          - wezterm
          - eza
          - starship
          - lsp-plugins-lv2
          - partitionmanager
          - noto-fonts-cjk
          - kwalletmanager
          - yubikey-manager
          - pam-u2f
          - lazygit
        state: present
