- name: 1Password
  hosts: localhost
  become: true
  tasks:
    - name: Add the key for the 1Password yum repository
      command:
        cmd: rpm --import https://downloads.1password.com/linux/keys/1password.asc

    - name: Add the 1Password yum repository
      command:
        cmd: sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'

    - name: Install 1Password
      dnf5:
        name: 1password
        state: present
