- name: Fedora
  hosts: localhost
  become: true
  tasks:
    - name: Enable third party repos
      dnf5:
        name:
          - fedora-workstation-repositories
        state: present

    - name: Enable Google Chrome repo
      raw: sudo dnf config-manager setopt google-chrome.enabled=1

    - name: Install programs from dnf
      dnf5:
        name:
          - steam
          - fastfetch
          - neovim
          - gh
          - git
          - stow
          - btop
          - easyeffects
          - mangohud
          - docker
          - docker-compose
          - gamemode
          - solaar
          - zsh
          - rustup
          - golang
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - google-chrome-stable
          - audacity
          - pam-u2f
          - pamu2fcfg
          - vlc
          - fzf
        state: present

    - name: Set default yes in dnf.conf
      lineinfile:
        path: /etc/dnf/dnf.conf
        search_string: "defaultyes="
        line: "defaultyes=True"
        state: present
        backup: true
