- name: Fedora
  hosts: localhost
  become: true
  tasks:
    - name: Install programs from dnf
      dnf5:
        name:
          - steam
          - fastfetch
          - neovim
          - gh
          - git
          - stow
          - btop
          - easyeffects
          - mangohud
          - gamemode
          - solaar
          - zsh
          - eza
          - golang
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - google-chrome-stable
          - audacity
          - vlc
        state: present

    - name: Set default yes in dnf.conf
      lineinfile:
        path: /etc/dnf/dnf.conf
        search_string: "defaultyes="
        line: "defaultyes=True"
        state: present
        backup: true
