- name: RPM Fusion
  hosts: localhost
  become: true
  tasks:
    - name: Install rpm fusion
      raw: sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    - name: Enable openh264 library
      raw: sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1

    - name: AppStream metadata
      raw: sudo dnf update -y @core

    - name: Switch to full ffmpeg
      raw: sudo dnf swap -y ffmpeg-free ffmpeg --allowerasing

    - name: Install additional codecs
      raw: sudo dnf update -y @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

    - name: Hardware codecs with AMD (mesa)
      raw: |
        sudo dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld
        sudo dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
        sudo dnf swap -y mesa-va-drivers.i686 mesa-va-drivers-freeworld.i686
        sudo dnf swap -y mesa-vdpau-drivers.i686 mesa-vdpau-drivers-freeworld.i686

    - name: Various firmwares
      raw: |
        sudo dnf install -y rpmfusion-nonfree-release-tainted
        sudo dnf --repo=rpmfusion-nonfree-tainted install -y "*-firmware"
