- name: Edit Steam config
  hosts: localhost
  tasks:
    - name: Make sure steam has started once to generate config files
      shell: timeout 8 steam
      register: result
      failed_when: result.rc != 124

    - name: Fix steam download speed
      lineinfile:
        path: "{{ ansible_env.HOME }}/.steam/steam/steam_dev.cfg"
        search_string: "@nClientDownloadEnableHTTP2PlatformLinux"
        line: "@nClientDownloadEnableHTTP2PlatformLinux 0"
        create: true

    - name: Get number of threads
      command: nproc
      register: nproc_output

    - name: Enable shaders to use all cores
      lineinfile:
        path: "{{ ansible_env.HOME }}/.steam/steam/steam_dev.cfg"
        search_string: "unShaderBackgroundProcessingThreads"
        line: "unShaderBackgroundProcessingThreads {{ nproc_output.stdout }}"
