- name: YubiKey
  hosts: localhost
  tasks:
    - name: Check for YubiKey presence
      ansible.builtin.shell:
        cmd: ykman list
      register: ykman_result

    - name: If YubiKey is plugged in; configure it
      when: ykman_result.stdout != ""
      block:
        - name: Ensure there is a u2f_keys file
          ansible.builtin.file:
            path: ~/.config/Yubico/u2f_keys
            state: touch
          register: u2f_keys_file

        - name: Configure primary YubiKey
          when: u2f_keys_file.size == 0
          register: primary_yubikey
          ansible.builtin.shell:
            cmd: pamu2fcfg > ~/.config/Yubico/u2f_keys

        - when: primary_yubikey.changed
          block:
            - register: setup_backup_prompt
              ansible.builtin.pause:
                prompt: "Would you like to setup a backup YubiKey now? [y/N]"

            - name: Configure backup YubiKey
              when: setup_backup_prompt.user_input == 'y' or setup_backup_prompt.user_input == 'Y'
              ansible.builtin.shell:
                cmd: pamu2fcfg -n >> ~/.config/Yubico/u2f_keys

        - name: Make sure authselect is on local profile
          register: authselect_current_profile
          ansible.builtin.shell:
            cmd: 'authselect current | grep "Profile ID: local" || true'

        - when: 'authselect_current_profile.stdout == "Profile ID: local"'
          block:
            - name: Determine if with-pam-u2f is enabled
              register: is_with_pam_u2f_enabled
              ansible.builtin.shell:
                cmd: authselect current | grep -o "with-pam-u2f" || true

            - when: is_with_pam_u2f_enabled.stdout == ""
              become: true
              block:
                - name: Enable with-pam-u2f
                  ansible.builtin.shell:
                    cmd: authselect enable-feature with-pam-u2f

                - name: Apply authselect changes
                  ansible.builtin.shell:
                    cmd: authselect apply-changes --backup=ansible
